# 1.1 Proyecto 1

# 1.2 Objetivos

## 1.2.1 Objetivo general
## 1.2.2 Objetivos especificos 


# 1.3 Introducción
#### En una construcción de un edificio que se encuentra en la fase de la cimentación. Se deben excavar dos tipos de elementos, zapatas y contratrabes.
#### Esta excavación se debe realizar en dos etapas, la primera con maquinaria y la segunda a mano pues debe afinar la capa de tierra.  Para realizar las zapatas se necesita un tiempo de maquinaria de 20 minutos y para las contratrabes de 30 minutos.-
#### Para afinar las zapatas manualmente se requiere de 20 minutos, mientras que para las contratrabes se requiere de 10 minutos.

#### Al mes tenemos disponibilidad del equipo manual de 100 horas y la maquinaria tiene una disponibilidad de 80 horas para este trabajo. La constructura obtiene una ganancia de 15 dolares de la excavación de zapatas y de 10 dolares por las contratrabes.
#### Debemos planificar la producción de m3 de excavación para obtener la máxima utilidad.

# 1.4 Modelo que representa el problema


#### El primer paso es definir las variables:

x1= m3 de excavación de zapata.
x2= m3 de excavación de contratrabe.


#### Para solucionar este problema debemos determinar la funcionar de costo la cual sería:

                               f(c)= 15x1 + 98x2
                               
#### Definimos las restricciones del problema:                               
                                

#### Reescribimos nuestra función como vectores:

                               

# 1.5 Solución del problema de optimización

In [8]:
# Importar numpy para crear matrices
import numpy as np

In [36]:
# Crear las matrices para resolver el problema
c = np.array([15, 10])
b = np.array([-100, -80])
A = np.array([[-.333, -0.5],
             [-0.333, -0.166]])

In [37]:
c,b,A

(array([15, 10]),
 array([-100,  -80]),
 array([[-0.333, -0.5  ],
        [-0.333, -0.166]]))

In [38]:
# Resolverlo utilizando linprog
sol_exc = opt.linprog(c, A_ub=A, b_ub=b)

In [39]:
# Mostrar el resultado
sol_exc

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 3754.6528564492633
              x: [ 2.104e+02  5.988e+01]
            nit: 2
          lower:  residual: [ 2.104e+02  5.988e+01]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [-7.552e+00 -3.749e+01]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

In [40]:
# Extraer el vector solución
x = sol_exc.x
x

array([210.39003075,  59.88023952])

# 1.6 Visualización de la solucion